name: build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [buster, bullseye, unstable]
    env:
      DISTRIBUTION: ${{ matrix.distribution }}
    steps:
      - uses: actions/checkout@v2
      - name: Determine latest upstream tag
        run: |
          UPSTREAM_DATED_TAG=$(curl -s 'https://hub.docker.com/v2/repositories/arm64v8/debian/tags?page_size=100' | jq -r '.results[]|.name' | grep -P "$DISTRIBUTION-\d{8}-slim" | sort -r | head -1)
          DATED_TAG=${UPSTREAM_DATED_TAG%-slim}
          echo name=UPSTREAM_DATED_TAG::$UPSTREAM_DATED_TAG >> "$GITHUB_ENV"
          echo name=DATED_TAG::$DATED_TAG >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          build-args: UPSTREAM_TAG=${{ env.UPSTREAM_DATED_TAG }}
          tags: |
            zmwangx/arm64v8-rust-ffmpeg:${{ env.DISTRIBUTION }}
            zmwangx/arm64v8-rust-ffmpeg:${{ env.DATED_TAG }}
            ghcr.io/zmwangx/arm64v8-rust-ffmpeg:${{ env.DISTRIBUTION }}
            ghcr.io/zmwangx/arm64v8-rust-ffmpeg:${{ env.DATED_TAG }}
          push: ${{ github.ref == 'refs/heads/master' }}
